"""Assurance / red-team scaffolding — the Layer-2 AI Assurance Loop.

Home of the mock vulnerable payments agent (KS-0301) that Garak probes and
Guardrails will patch, plus the canonical vulnerability SIGNATURE that the future
Garak probe (KS-0303) and the Layer-1 fraud fixture (KS-0403) both import — one
source of truth for the planted flaw. Later, the in-repo driver that invokes Garak
as an external subprocess (ADR-0003) lives here too.

This layer may depend on the core and the LLM edge; the core never imports it.
"""

from __future__ import annotations

from .agent import (
    AGENT_NAME,
    LAYER,
    LEDGER_ACTION,
    TOOLS,
    VULNERABLE_SYSTEM_PROMPT,
    AgentRun,
    Transaction,
    TransferIntent,
    exploit_fired,
    run_agent,
)
from .framework import (
    AttackChannel,
    AttackSide,
    CrimeSide,
    FinancialProjection,
    PairBinding,
    SeamDriftError,
    SeamEvent,
    SeamPair,
    SeamResult,
    bind,
    financial_projection_for,
    project_financial,
)
from .garak_probe import (
    CURATED_PROBES,
    FAMILY_MAPPINGS,
    PINNED_GARAK_VERSION,
    PROMPT_INJECTION_FAMILIES,
    GarakError,
    GarakFinding,
    GarakMappingError,
    MappedFinding,
    RegulatoryMapping,
    ScanConfig,
    found_our_vulnerability,
    map_finding,
    parse_report,
    record_finding,
    run_scan,
    scan_mock_agent,
)
from .pairs import REGISTERED_PAIRS
from .referenced import REFERENCED_ASSURANCE, ReferencedAssurance
from .remediation import (
    FINANCIAL_TIGHTENING,
    FINANCIAL_TIGHTENING_CONTROL,
    GUARDRAIL_PATCH,
    GUARDRAIL_PATCH_CONTROL,
    REMEDIATION_MENU,
    Remediation,
    RemediationContext,
    RemediationOutcome,
    SeamSide,
    financial_detection_gap,
    newly_flagged_by_tightening,
    tighten_financial_detection,
)
from .seam import (
    P1_PAIR,
    SeamError,
    SeamProof,
    prove_seam,
    resolve_signature,
    seam_fraud_stream,
)
from .seam_p2 import (
    P2_PAIR,
    p2_fraud_stream,
    resolve_forwarding_signature,
)
from .seam_p3 import (
    P3_PAIR,
    p3_fraud_stream,
    resolve_large_transfer_signature,
)
from .seam_p4 import (
    BOUNDARY_STATEMENT,
    P4_PAIR,
    p4_exfil_event,
    resolve_exfil_signature,
)
from .seam_p5 import (
    P5_PAIR,
    p5_tool_misuse_stream,
    resolve_tool_misuse_signature,
)
from .signature import (
    CANONICAL_EXFIL_MEMO,
    CANONICAL_FORWARDING_EXPLOIT,
    CANONICAL_LARGE_TRANSFER_EXPLOIT,
    CANONICAL_MEMO_EXPLOIT,
    CANONICAL_TOOL_MISUSE_MEMO,
    EXFIL_INJECTION_SIGNATURE,
    MEMO_FORWARDING_SIGNATURE,
    MEMO_INJECTION_SIGNATURE,
    MEMO_LARGE_TRANSFER_SIGNATURE,
    TOOL_MISUSE_SIGNATURE,
    ExploitOutcome,
    InjectionField,
    InjectionMechanism,
    MaliciousMemoExample,
    VulnerabilitySignature,
)

__all__ = [
    "AGENT_NAME",
    "BOUNDARY_STATEMENT",
    "CANONICAL_EXFIL_MEMO",
    "CANONICAL_FORWARDING_EXPLOIT",
    "CANONICAL_LARGE_TRANSFER_EXPLOIT",
    "CANONICAL_MEMO_EXPLOIT",
    "CANONICAL_TOOL_MISUSE_MEMO",
    "CURATED_PROBES",
    "EXFIL_INJECTION_SIGNATURE",
    "FAMILY_MAPPINGS",
    "LAYER",
    "LEDGER_ACTION",
    "MEMO_FORWARDING_SIGNATURE",
    "MEMO_INJECTION_SIGNATURE",
    "MEMO_LARGE_TRANSFER_SIGNATURE",
    "P1_PAIR",
    "P2_PAIR",
    "P3_PAIR",
    "P4_PAIR",
    "P5_PAIR",
    "PINNED_GARAK_VERSION",
    "FINANCIAL_TIGHTENING",
    "FINANCIAL_TIGHTENING_CONTROL",
    "GUARDRAIL_PATCH",
    "GUARDRAIL_PATCH_CONTROL",
    "REFERENCED_ASSURANCE",
    "REGISTERED_PAIRS",
    "REMEDIATION_MENU",
    "Remediation",
    "RemediationContext",
    "RemediationOutcome",
    "SeamSide",
    "financial_detection_gap",
    "newly_flagged_by_tightening",
    "tighten_financial_detection",
    "ReferencedAssurance",
    "PROMPT_INJECTION_FAMILIES",
    "TOOLS",
    "TOOL_MISUSE_SIGNATURE",
    "VULNERABLE_SYSTEM_PROMPT",
    "AgentRun",
    "AttackChannel",
    "AttackSide",
    "CrimeSide",
    "ExploitOutcome",
    "FinancialProjection",
    "GarakError",
    "GarakFinding",
    "GarakMappingError",
    "InjectionField",
    "InjectionMechanism",
    "MaliciousMemoExample",
    "MappedFinding",
    "PairBinding",
    "RegulatoryMapping",
    "ScanConfig",
    "SeamDriftError",
    "SeamError",
    "SeamEvent",
    "SeamPair",
    "SeamProof",
    "SeamResult",
    "Transaction",
    "TransferIntent",
    "VulnerabilitySignature",
    "bind",
    "exploit_fired",
    "financial_projection_for",
    "found_our_vulnerability",
    "map_finding",
    "p2_fraud_stream",
    "p3_fraud_stream",
    "p4_exfil_event",
    "p5_tool_misuse_stream",
    "parse_report",
    "project_financial",
    "prove_seam",
    "record_finding",
    "resolve_exfil_signature",
    "resolve_forwarding_signature",
    "resolve_large_transfer_signature",
    "resolve_signature",
    "resolve_tool_misuse_signature",
    "run_agent",
    "run_scan",
    "seam_fraud_stream",
    "scan_mock_agent",
]
